### ISSUE TITLE
Review new vue rules

### ISSUE THREAD

**Issue by edg2s** [wikimedia/jscs-preset-wikimedia#392]
https://github.com/vuejs/eslint-plugin-vue/releases

**Comment by catrope** [comment]
We should be able to safely upgrade without making changes, because none of the new rules are enabled by default (in fact, upstream hasn't updated the "recommended" set of rules in 8 months).

Of the new rules, these are the ones I think we should enable:
- [no-invalid-model-keys](https://eslint.vuejs.org/rules/no-invalid-model-keys.html)
- [no-unused-refs](https://eslint.vuejs.org/rules/no-unused-refs.html); this will misfire sometimes when people use dynamic refs or use refs through mixins, but those are advanced cases where the rule can be disabled on a case-by-case basis.
- [no-export-in-script-setup](https://eslint.vuejs.org/rules/no-export-in-script-setup.html) (Vue 3 only)
- [valid-define-emits](https://eslint.vuejs.org/rules/valid-define-emits.html) (Vue 3 only)
- [valid-define-props](https://eslint.vuejs.org/rules/valid-define-props.html) (Vue 3 only)
- [no-use-computed-property-like-method](https://eslint.vuejs.org/rules/no-use-computed-property-like-method.html)
- [valid-v-memo](https://eslint.vuejs.org/rules/valid-v-memo.html) (Vue 3 only)
- [no-v-text](https://eslint.vuejs.org/rules/no-v-text.html)
- [no-useless-template-attributes](https://eslint.vuejs.org/rules/no-useless-template-attributes.html)

Some non-new rules that we should also enable:
- [v-on-function-call](https://eslint.vuejs.org/rules/v-on-function-call.html)
- [valid-next-tick](https://eslint.vuejs.org/rules/valid-next-tick.html)
- [no-deprecated-v-is](https://eslint.vuejs.org/rules/no-deprecated-v-is.html) (Vue 3 only)
- [no-duplicate-attr-inheritance](https://eslint.vuejs.org/rules/no-duplicate-attr-inheritance.html)
- [no-multiple-objects-in-class](https://eslint.vuejs.org/rules/no-multiple-objects-in-class.html)
- [no-reserved-component-names](https://eslint.vuejs.org/rules/no-reserved-component-names.html)
- [no-unregistered-components](https://eslint.vuejs.org/rules/no-unregistered-components.html)
- [no-unused-properties](https://eslint.vuejs.org/rules/no-unused-properties.html)
- [no-useless-mustaches](https://eslint.vuejs.org/rules/no-useless-mustaches.html)
- [no-useless-v-bind](https://eslint.vuejs.org/rules/no-useless-v-bind.html)

In my copious spare time I may also submit a PR upstream to add some of these things to the recommended set.
